// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config'
import { defineConfig } from 'prisma/config'

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // ה-CLI (מיגרציות) חייב חיבור ישיר — ה-pooler (pgbouncer, פורט 6543) גורם לתקיעה.
    url: process.env['DIRECT_URL'] ?? process.env['DATABASE_URL'],
  },
})
